all:
  vars:
    ansible_ssh_user: ubuntu
    ansible_ssh_common_args: >
      -o StrictHostKeyChecking=no
      -o UserKnownHostsFile=/dev/null
    ansible_ssh_private_key_file: /opt/seccamp.pem
  children:
    student:
      hosts:
        54.168.204.100:
